game_shop/game_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop_app.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game_shop/shop_app/urls.py
from django.urls import path
from . import views

app_name = "shop_app"

urlpatterns = [
    path("", views.main, name="main"),
    path("<int:page>", views.main, name="main_paginate"), 
    path("search/", views.search_results, name="search_result"),
    path("<str:game_title>/", views.game_detail, name="game_detail"),
    path('genre/<int:genre_id>/', views.genre_detail, name='genre_detail'), 
]

game_shop/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

game_shop/shop_app/models.py
from django.db import models


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Game(models.Model):
    path = models.ImageField(upload_to='uploads/', default='')
    title = models.CharField(max_length=255, null=True, unique=True)
    price = models.PositiveIntegerField(null=True)
    date_of_release = models.DateField(null=True)
    game_description = models.TextField(null=True)
    genre = models.ManyToManyField(Genre)
    platform = models.CharField(max_length=50, null=True)
    os_requirements = models.TextField(null=True)
    processor_requirements = models.CharField(max_length=255, null=True)
    memory_requirements = models.CharField(max_length=255, null=True)
    graphics_card_requirements = models.CharField(max_length=255, null=True)
    disk_space_requirements = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.title

game_shop/users/models.py
from PIL import Image
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default="default_avatar.png", upload_to="profile_images")

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

game_shop/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import Profile


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Profile
        fields = ['avatar']

game_shop/shop_app/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from .models import Game, Genre
from django.core.paginator import Paginator



def main(request, page=1):
    games = Game.objects.all()
    genres = Genre.objects.all().order_by('name')
    per_page = 48
    paginator = Paginator(list(games), per_page)
    games_on_page = paginator.page(page)
    return render(request, 'shop_app/index.html', context={'games':games_on_page, 'genres': genres})


def game_detail(request, game_title):
    game = get_object_or_404(Game, title=game_title)
    return render(request, 'shop_app/game_detail.html', context={'game_detail': game})


def genre_detail(request, genre_id):
    genre = get_object_or_404(Genre, id=genre_id)
    games = genre.game_set.all()  # Получите список игр, связанных с выбранным жанром
    if not games:
        return render(request, 'shop_app/genre_none.html')
    return render(request, 'shop_app/genre_detail.html', {'genre': genre, 'games': games})


def search_results(request):
    query = request.GET.get('q')
    results = Game.objects.filter(title__icontains=query)  # Ищем игры, в названии которых есть текст из запроса
    return render(request, 'shop_app/search_results.html', {'results': results})

game_shop/users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin

from .forms import RegisterForm, LoginForm, ProfileForm


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='shop_app:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='shop_app:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='shop_app:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='shop_app:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='shop_app:main')


@login_required
def profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users:profile')

    profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'users/profile.html', {'profile_form': profile_form})

game_shop/shop_app/templates/shop_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Game Shop Ltd &#xae</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/modern-normalize/1.0.0/modern-normalize.min.css">
    {%load static%}
    <link rel="stylesheet" href="{% static 'shop_app/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'shop_app/styles.css' %}">

</head>


<body>
     <header>
      <div class="container">
        <section class="title">
         <div class="title-wrap">
         <div class="logo">
                <a href="{% url 'shop_app:main' %}" style="text-decoration: none">Pavlik <span>Ravlik&#xae</span></a>
         </div>
         
         <div class="login-wrap">
         {% if user.is_authenticated %}
         
         <a href="{% url 'users:profile' %}" class="login">Profile {{user.username}} {{user.avatar}}</a>
         <a href="{% url 'users:logout' %}" class="signup">logout</a>
         {% else %}
         <a href="{% url 'users:signup' %}" class="signup">SignUp</a>
         <a href="{% url 'users:login' %}" class="login">Login</a>
         {% endif %}
         </div>
         </div>
         </div>

        <div class="input-line">
         
      <div class="input-wrap">
        <div class="container">        
         <form class='search' method="get" action="{% url 'shop_app:search_result' %}">
          <input type="text" name='q' placeholder="Искать здесь...">
          <button type="submit"></button>
         </form>
        </div>
       </div>
      
      </header>

        {%block content%}
        {%endblock%}
        

        {% block genre %}
        {%endblock%}
        
        {%block result%}
        {%endblock%}

    <footer>
        <p>Pavlik-Ravlik Corporation, All Right Reserved</p>
    </footer>
      
</body>
</html>

game_shop/shop_app/templates/shop_app/game_detail.html
{% extends 'shop_app/base.html' %}
{% block content %}
<main>
    <div class="container">
      <section class="main">
        <div class="card">
        <ul class="card-set">
<div class="game-details">
    <h3 class="game-title">{{ game_detail.title }}</h3>

    <div class='game-detailes-info'>
        <div class="game-info">
            <img src="/media/{{game_detail.path}}" alt="Poster" width="200" height="300">
            <p><strong>Price:</strong> {{ game_detail.price }} $</p>
            {% if user.is_authenticated %}
            <button type="submit" > Buy</button>
            {% else %}
            <p> You must be a authenticated for buy this game.</p>
            {% endif %}       
        </div>
    
    <div>
        <p><strong>Date of realise:</strong> {{ game_detail.date_of_release }}</p>
        <p><strong>Genre:</strong>
        {% for genre in game_detail.genre.all %}
            {{ genre.name }}
            {% if not forloop.last %}, {% endif %}
        {% endfor %}</p>
        <p><strong>Platform:</strong> {{ game_detail.platform }}</p>
        <p><strong>OC:</strong> {{ game_detail.os_requirements }}</p>
        <p><strong>Memory:</strong> {{ game_detail.memory_requirements }}</p>
        <p><strong>GPU:</strong> {{ game_detail.graphics_card_requirements }}</p>
        <p><strong>Free space on disc:</strong> {{ game_detail.disk_space_requirements }}</p>
    </div>

    </div>
    <p><strong>Description:</strong> {{ game_detail.game_description }}</p>
</div>
</main>
{% endblock %}

game_shop/shop_app/templates/shop_app/genre_detail.html
{% extends 'shop_app/base.html' %} 
{% block genre %}

<main>
  <div class="container">
    <section class="main">
      <div class="card">
      <ul class="card-set">
  {%for game in games%}
    <li class="item">
        <img src="/media/{{game.path}}" alt="Poster" width='161' height='230'>
        <div class="game-description">
          <a href="/{{game.title}}">
        <h3 class="game-title">{{game.title}}</h3>
      </a> 
        <p class="game-price">$ {{game.price}}</p>
        </div>
      </li>
  {% endfor %}
    </section>
    </div>
  </main>
        
{% endblock %}

game_shop/shop_app/templates/shop_app/genre_none.html
{% extends 'shop_app/base.html' %} 
{% block genre %}

<main>
  <div class="container">
    <section class="main">
      <div class="card">
      <ul class="card-set">
        <h1> There are no games according to your chosen genre! </h1>
    </section>
    </div>
  </main>
        
{% endblock %}

game_shop/shop_app/templates/shop_app/index.html
{% extends 'shop_app/base.html' %} 
{% block content %}

<main>
    <div class="container">
        <section class="main">
          <div class="card">
          <ul class="card-set">
      {%for game in games%}
        <li class="item">
            <img src="/media/{{game.path}}" alt="Poster" width='161' height='230'>
            <div class="game-description">
              <a href="/{{game.title}}">
            <p class="game-title">{{game.title}}</p>
          </a> 
            <p class="game-price">$ {{game.price}}</p>
            </div>
          </li>
      {% endfor %}

      
      <div class="btn-pagination">

        {% if games.has_previous %}
            <a href="{% url 'shop_app:main_paginate' games.previous_page_number %}" class="btn-prev"> ← Previous</a>
        {% endif %}
        
        {% if games.has_next %}
            <a href="{% url 'shop_app:main_paginate' games.next_page_number %}" class="btn-next"> → Next</a>
        {% endif %}
        </div>
      </div>

      <div class="main-menu-wrap">
        <ul class="main-menu">
          {% for genre in genres %}
          <li class="menu-item"><a href="{% url 'shop_app:genre_detail' genre.id %}">{{ genre.name }}</a></li>
          {% endfor %}
          </ul>
        </div>
      </section>
    </div>
  </main>

     
{% endblock %}

game_shop/shop_app/templates/shop_app/search_results.html
{% extends 'shop_app/base.html' %} 
{% block result %}

<main>
    <div class="container">
      <section class="main">
        <div class="card">
        <ul class="card-set">
    {%for game in results%}
      <li class="item">
          <img src="/media/{{game.path}}" alt="Poster" width='161' height='230'>
          <div class="game-description">
            <a href="/{{game.title}}">
          <h3 class="game-title">{{game.title}}</h3>
        </a> 
          <p class="game-price">$ {{game.price}}</p>
          </div>
        </li>
    {% endfor %}
      </section>
      </div>
          
{% endblock %}

game_shop/users/templates/users/login.html
{% extends "shop_app/base.html" %}

{% block content %}
<div class="container">
    <section class="main">
      <div class="card">
      <ul class="card-set">
        <div>
            <h2>Login</h2>
        </div>

        {% if messages %}
        <div>
            {% for message in messages %}
            <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}

        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <div>
                <label> Username:
                    {{ form.username }}
                </label>
            </div>

            <div>
                <label>Password:
                    {{ form.password }}
                </label>
            </div>

            <div class="grid">
                <button type="submit">Submit</button>
                <button type="reset" class="secondary">Reset</button>
                <a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
            </div>
        </form>
    </section>
</div>
{% endblock %}

game_shop/users/templates/users/password_reset.html
{% extends "shop_app/base.html" %}

{% block content %}

<div class="container">
    <section class="main">
      <div class="card">
      <ul class="card-set">
        <h2>Password reset</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Request password reset</button>
        </form>
        </div>
    </section>
</div>

{% endblock %}

game_shop/users/templates/users/password_reset_complete.htm
{% extends "shop_app/base.html" %}

{% block content %}

<div class="container">
    <section class="main">
      <div class="card">
      <ul class="card-set">
        <h2>Password reset complete!</h2>
        </div>
    </section>
</div>

{% endblock %}

game_shop/users/templates/users/password_reset_confirm.html
{% extends "shop_app/base.html" %}

{% block content %}

<div class="container">
    <section class="main">
      <div class="card">
      <ul class="card-set">
        <h2>Enter new password</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save new password</button>
        </form>
        </div>
    </section>
</div>

{% endblock %}

game_shop/users/templates/users/password_reset_done.html
{% extends "shop_app/base.html" %}

{% block content %}

<div class="container">
    <section class="main">
      <div class="card">
      <ul class="card-set">
        <h2>Password reset request sent</h2>
        <p>We've emailed you with instructions on how to reset your password.</p>
        </div>
    </section>
</div>

{% endblock %}

game_shop/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

game_shop/users/templates/users/profile.html
{% extends 'shop_app/base.html' %}

{% block content %}
<main>
    <div class="container">
        <section class="main">
            <div class="card">
            <ul class="card-set">
    
        <h1>Profile page: {{user.username}}</h1>
        <img src="{{ user.profile.avatar.url }}" alt="avatar of user"/>


    {% if messages %}
    <div>
        {% for message in messages %}
        <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-5">
                <div class="form-group">
                    <label class="small mb-1">Change Avatar:</label>
                    {{ profile_form.avatar }}
                    <span>{{ profile_form.errors.avatar }}</span>
                </div>
            </div>
        </div>
        <div class="grid">
            <button type="submit">Save Changes</button>
            <button type="reset" class="secondary">Reset</button>
        </div>
    </form>
                </div>
            </section>
        </div>
    </main>

{% endblock %}

game_shop/users/templates/users/signup.html
{% extends "shop_app/base.html" %}

{% block content %}
<div class="container">
    <section class="main">
      <div class="card">
      <ul class="card-set">
        <div>
            <h2>Sign Up</h2>
        </div>

        <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            <div>
                <label> Username:
                    {{ form.username }}
                </label>
                <span>{{ form.errors.username }}</span>
            </div>
            <br>
            <div>
                <label> Password:
                    {{ form.password1 }}
                </label>
                <span>{{ form.errors.password1 }}</span>
            </div>
            <div>
                <label> Password confirmation:
                    {{ form.password2 }}
                </label>
                <span>{{ form.errors.password2 }}</span>
            </div>
            <div class="grid">
                <button type="submit">Submit</button>
                <button type="reset" class="secondary">Reset</button>
            </div>
        </form>
    </section>
</div>
{% endblock %}